---
title: "Expert advice from experts"
author:
- name: Professor Marie Curie
  degrees: Nobel Prize, PhD
  email: mcurie.notreal@gmail.com
- name: Dr Pierre Curie
  degrees: Nobel Prize, PhD
phone: (03) 9905 2478
email: BusEco-Econometrics@monash.edu
organization: Acme Corporation
bibliography: references.bib
format: html
---

::: {#fig-flowchart fig-cap="Project approval gate flowchart"}
```{mermaid}
flowchart LR
  A(BNI) --> B(PBC)
  B --> C{BCA} --> D(Stage 1) --> E(Stage 2) --> F(Stage 3)
```
:::


::: {#fig-flowchartkpi fig-cap="KRA-KPI flowchart"}
```{mermaid}
flowchart TB
  A{KRA} --> B(Timeliness)
  A{KRA} --> C(Sustainability)
  A{KRA} --> D(Safety)
  A{KRA} --> E(Social procurement)
  
  B --> F[KPIs]
  C --> G[KPIs]
  D --> H[KPIs]
  E --> I[KPIs]
```
:::



```{r}
project_numbers <- project_data %>% group_by(delivery_program,yearmonth(bca)) %>% summarise(Total = sum(ffc))

project_tsibble <- project_numbers %>% # Tsibble created based on BCA year
   as_tsibble(index = `yearmonth(bca)`,key = delivery_program) %>% fill_gaps(Total = 0L) # Fill NA with 0
```
```{r}
gg_season(project_tsibble)
```

